### ISSUE TITLE
Staking App goes blank when wallet is connected and dials is clicked (Edge)

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#144]
**Describe the bug**
The staking App goes blank when the wallet is connected and dials is clicked

**To Reproduce**
1. Go to https://staking.mstable.org/#/
2. Connect Connect Wallet
3. Click Dials in Menu
4. Page goes blank

**Expected behaviour**
Should navigate normally to dials and show content

**Screenshots**
![Screen Shot 2022-05-09 at 22 24 31](https://user-images.githubusercontent.com/69167058/167443267-16631902-0d1e-4449-8dc4-d8cfeeb76260.png)
![Screen Shot 2022-05-09 at 22 24 42](https://user-images.githubusercontent.com/69167058/167443317-0501fc88-e14b-4b9e-bba4-58ac0e1bad52.png)

**Desktop (please complete the following information):**
 - OS: MacOS and Windows tested
 - Browser Edge
 - Version 101.0.1210.39 (Official build) (x86_64)

**Additional context**

**Comment by rafaelugolini** [comment]
@dimsome were you able to reproduce? I couldn't reproduce but looks like the PR of @toniocodo fixes it

**Comment by dimsome** [comment]
@rafaelugolini Yes, see screenshots. 

Is there a staging link for the governance app?

**Comment by toniocodo** [comment]
I was also looking for it, by default only protocol app is accessible... 
@rafaelugolini I was only able to reproduce by launching app locally, issue doesn't appear in prod. It is due to the activeDial "Dial 18" that doesn't seem to have metadata, I don't know if it's available in prod already

**Comment by dimsome** [comment]
@toniocodo The issue was there before Dial 18 was added. Note: It's something that happens with Edge only.

**Comment by toniocodo** [comment]
yes, I suppose any `activeDial` object without metadata would cause this issue. My PR fixes that, it doesn't address the metadata lack cause though... I need additional information regarding business logic for that 😅

**Comment by dimsome** [comment]
@toniocodo 
https://github.com/mstable/mstable-v1-backlog/issues/47

**Comment by rafaelugolini** [comment]
https://mstable-apps-governance--pr145-fix-144-staking-app-v6k1lwdr.web.app

**Comment by dimsome** [comment]
Ok, can confirm: The issue is fixed! Thanks
