### ISSUE TITLE
Wallet and Network behaviour is inconsistent/unexpected

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#147]
---
name: Bug report
about: Create a report to help us improve
title: Wallet and Network behaviour is inconsistent/unexpected
labels: UI, staking, app
---

**Describe the bug**
The Wallet behaviour is unexpected for some actions. This applied to both, the staking and the main app. But point 5 is specific to the staking app.

- [ ] **When changing to a non-supported network from MM, the app prompts to change to Ethereum back**

Should not prompt to change the network, because this app might be in another Tab and the users try to change network using another app. After rejection, there is no indication in the app that the wrong network has been selected. The wrong network appears for a split second but changes back to the default network.

- [x] **When selecting a non-supported network, the app has no indication that a non-supported network is selected.**

Should have something to tell the user that the current network is not supported

- [x] **When Polygon is selected in MM, upon opening the app it prompts to change to mainnet (should detect that Polygon is selected)**

This does not happen every time, I am not sure what triggers this.

- [ ] **Staking App allows Polygon to have selected, but it doesn't support polygon.**

The app is still normally accessible but all the content does not get loaded, no indication that the network is not supported

- [x] **When changing networks, the wallet shows for a split second that the wrong network is connected**

This should really happen only when a wrong network is selected and persist until it is changed

- [x] **When changing from polygon to mainnet, subgraph errors appear.**

![Screen Shot 2022-05-12 at 18 12 36](https://user-images.githubusercontent.com/69167058/168060797-81b31776-1e3d-4e34-97b0-91a46ec2bde6.png)

- [ ] **When promoting to change networks from the app, MM change network appears and elements of the APP get rerendered.**

**Comment by ThomasDev62** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by dimsome** [comment]
@toniocodo I changed the points to checkboxes, feel free to create sub-issues from it. Let's sync soon to look into one particular.

**Comment by toniocodo** [comment]
yes, this issue is a pretty hard one, it requires for me to get deeper in the codebase and fully understand how contexts are build upon each others... Still reading a lot for now, I'll get in touch with you when I'll get a better understanding.

**Comment by toniocodo** [comment]
Some points of this issues are solved by #181, probably best to re-assess after merging

**Comment by dimsome** [comment]
`When selecting a non-supported network, the app has no indication that a non-supported network is selected.`

behaviour is now that the app disconnects from the wallet, which is not the best, but certainly better than before.
Marked other points as complete as well.

**Comment by dimsome** [comment]
Yeah, let's just accept the way it is now and not overcomplicate it.

**Comment by dimsome** [comment]
Status is done, can we close this issue?
