### ISSUE TITLE
[Staking App] Process to adjust or add delegate Profile

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#157]
**Is your feature request related to a problem? Please describe.**
Currently, we have no process when it comes to adding new delegates or adjusting the profiles (Bio, profile picture). For the future to remain decentralised and to support delegation by known individuals we should have a way to add new profiles and adjust existing ones.

**Describe the solution you'd like**
A dedicated UI would be probably to cumbersome, but I would imagine a repo where individuals can add themselves into a JSON file that we then can use to upload periodically when required.

![Uploading Screen Shot 2022-05-20 at 13.14.59.png…]()

**Comment by dimsome** [comment]
A new repo has been created.

https://github.com/mstable/mStable-staking-delegates

**Comment by dimsome** [comment]
@rafaelugolini could we change the visibility of the repo to public? I have no authorization to do so.

https://github.com/mstable/mStable-staking-delegates

**Comment by rafaelugolini** [comment]
@dimsome done :)
