### ISSUE TITLE
[App] Move deprecated pools

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#162]
**Is your feature request related to a problem? Please describe.**
Move deprecated pool either to the bottom or a new tab?

**Describe the solution you'd like**
The deprecated pool should be not at the top of the page. The easiest solution is just to move the pool to the bottom. 

**Additional context**
![Screen Shot 2022-05-23 at 11 42 46](https://user-images.githubusercontent.com/69167058/169744891-0012e52e-79b1-4c36-85a0-6e8ba2056dcd.png)

**Comment by talentdev0807** [comment]
James Wee
