### ISSUE TITLE
[App] While depositing, default to Vault

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#163]
**Is your feature request related to a problem? Please describe.**
A user wants in most cases to stake the tokens. The UI however defaults to the step before. (Save and Pools)

![Screen Shot 2022-05-23 at 11 50 01](https://user-images.githubusercontent.com/69167058/169745607-fac1acae-34b3-4380-905b-fa88108e45d6.png)

**Describe the solution you'd like**
Should directly select the Vault, similar when redeeming, should directly offer to redeem from the Vault. Alternatively, can fetch the balance and suggest to redeem from the Vault or Save (Pool).

**Comment by talentdev0807** [comment]
James Wee
