### ISSUE TITLE
[App] Clicking on the arrow should reverse the assets.

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#164]
**Is your feature request related to a problem? Please describe.**
A common pattern in UIs that offer swaps from one asset to the other is that the arrow in the middle can act as a button that can swap the assets. Should be able to click and reserves the order.

**In Save Page**
1. Go from deposit to redeem and vice versa
![Screen Shot 2022-05-23 at 11 53 34](https://user-images.githubusercontent.com/69167058/169745976-5de969b0-f302-477e-9880-50b3ad1afc8a.png)

**In Swap Page**
1. Arrow should reverse the assets, example screenshot: sUSD -> USDC, reverse to USDC to sUSD.
![Screen Shot 2022-05-23 at 11 53 53](https://user-images.githubusercontent.com/69167058/169746011-37c3ca20-46b8-49bd-aa24-493ae5a90450.png)

**Comment by talentdev0807** [comment]
Can I contribute on this one?

**Comment by dimsome** [comment]
> Can I contribute on this one?

Yup, feel free @talentdev0807
