### ISSUE TITLE
Polygon transaction estimation

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#194]
**Describe the bug**
When trying to send a transaction on Polygon some information is wrong: 
- Ethereum is displayed (should display matic)
- Transaction cost estimation is done with the Ethereum price, looks very expensive.

**To Reproduce**
1. Go to https://mstable.app/#/musd/swap
2. Select polygon
3. Try to swap
4. Click on Redeem/Swap
5. See Transaction modal.
![Screen Shot 2022-07-08 at 00 14 24](https://user-images.githubusercontent.com/69167058/177831837-2e9154e6-4462-46e3-afbe-2a688af2b9a6.png)

**Expected behavior**
Should estimate Polygon fees in Matic and change icon to Matic.

**Comment by dimsome** [comment]
I think the gas estimation is also based on Ethereum Mainnet

**Comment by dimsome** [comment]
![Screen Shot 2022-07-08 at 00 20 20](https://user-images.githubusercontent.com/69167058/177832807-27d0b05b-0a5e-4dfc-bc99-244c005fe1bf.png)
Sometimes this happens

**Comment by GhegethDev** [comment]
@dimsome Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.
