### ISSUE TITLE
Polygon gas estimation is always 30

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#198]
**Describe the bug**
The Gas estimation always returns 30 for standard, Fast, and Instant. Despite actually gas being higher. Maybe the gas API doesn't return proper values? 

Also: standard < Fast < Instant.

![Screen Shot 2022-07-15 at 17 32 45](https://user-images.githubusercontent.com/69167058/179206544-65ba76a1-1097-4773-912d-32584dccbd30.png)

**Comment by rafaelugolini** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/2651141/179457673-f84d7718-9998-421c-b7d0-22a4a2f52013.png">
The API is working fine
