### ISSUE TITLE
MTA Apy not correct when rewards are not updated

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#205]
**Describe the bug**
Many dials got disabled, however, the UI still shows the same APY for MTA rewards. This is because the rewards Rate does not get updated anymore. The UI has to be aware that if the last time the rewardsRate was updated longer than 7 days, the rewards are empty and no new rewards got added.

**To Reproduce**

https://mstable.app/#/mbtc/save

https://mstable.app/#/mbtc/pools

https://mstable.app/#/musd/pools

Also Single Pools Page, e.g. https://mstable.app/#/musd/pools/0x4eaa01974b6594c0ee62ffd7fee56cf11e6af936

**Expected behavior**

**Screenshots**

![Screen Shot 2022-08-29 at 15 14 41](https://user-images.githubusercontent.com/69167058/187155886-7b12de57-c6dd-4d97-a463-95d555909f0e.png)

![Screen Shot 2022-08-29 at 15 14 49](https://user-images.githubusercontent.com/69167058/187155912-ebca4903-1d6f-4ecf-a112-0d4c59773440.png)

![Screen Shot 2022-08-29 at 15 15 06](https://user-images.githubusercontent.com/69167058/187155963-175523bd-7f70-4e27-a307-5148d7812f7c.png)

**Comment by calvinkei** [comment]
hi @dimsome , just checking if this looks correct
<img width="1021" alt="Screenshot 2022-08-29 at 6 03 42 PM" src="https://user-images.githubusercontent.com/14106911/187177797-0e5c560c-8082-47ae-814b-240b571c4117.png">

**Comment by dimsome** [comment]
I think all of them should be now 0%. 

- Could we completely remove the Rewards APY if it's 0%, rather than displaying `-%`
- imBTC Save has some APY, true, but the Vault received the last MTA 11 Days ago: https://etherscan.io/address/0xf38522f63f40f9dd81abafd2b8efc2ec958a3016#tokentxns

**Comment by calvinkei** [comment]
@dimsome you mean removing the `Rewards APY` row like this?
<img width="1032" alt="Screenshot 2022-08-29 at 7 13 35 PM" src="https://user-images.githubusercontent.com/14106911/187188847-cb7fe1e9-941f-46b0-a5b5-4f8a4212ca7a.png">

**Comment by dimsome** [comment]
yup, that looks alright
