### ISSUE TITLE
[Staking App] Hold time not showing up in the quest 

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#216]
## Bug description

1. https://staking.mstable.app/#/quests
2. Needs to connect to a wallet that has staked and received a `timeMultiplier`

Hold time is always 1x. Does not reflect the real `timeMultiplier`

![photo_2022-02-17 13 21 11](https://user-images.githubusercontent.com/2651141/154480822-1b5289fa-c7e3-4ee3-88d9-f85783b669f8.jpeg)

## Acceptance Criteria

- [ ] Shows correct `timeMultiplier` for the connected account.

**Comment by biendeveloper** [comment]
Hi @dimsome Can you share with me an address that staked and received a `timeMultiplier` (address that can reproduce the issue)

**Comment by dimsome** [comment]
`0x3df1b295d394b6c77415e9659cc1a7dbcca76be7` @biendeveloper
